name: corgi

on:
  push:
    branches:
      - corgi

permissions:
  id-token: write     # Needed to request OIDC token
  contents: read      # Needed to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::385122037426:role/cicdRole  # Replace with your role ARN
        aws-region: us-east-1  # Or your region

    - name: Verify role was assumed
      run: aws sts get-caller-identity

    - name: s3 ls
      run: aws s3 sync s3://sitee47c1679c9f70e53 ./ttt

    - name: please work
      run: ls ./ttt
